name: Run cobol sample
on:
  workflow_dispatch:
  push:
    
jobs:
  run-sample-program:
    runs-on: ubuntu-latest
    container:
      image: opensourcecobol/opensourcecobol4j
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Show cobj version
        run: |
          cobj -version

      - name: Show diffutils version
        run: |
          diff -v

      - name: Create old files
        run: |
          cat *** Employee List *** > EMPLIST.old
          cat ID   Employee Name        Dpt Enter date >> EMPLIST.old
          cat ---- -------------------- --- ---------- >> EMPLIST.old
          cat 0012 Chiba Jiro            02 1999/04/01 >> EMPLIST.old
          cat 0013 Tokyo Taro            03 1997/04/01 >> EMPLIST.old
          cat 0014 Kanagawa Shiro        01 2012/04/01 >> EMPLIST.old
          cat 0015 Niigata  Goroo        02 2001/04/01 >> EMPLIST.old
          cat EOF >> EMPLIST.old

      - name: Run HELLO
        run: |
          cobj HELLO.cbl
          echo mytest | java HELLO

      - name: Run EMPWRITE and EMPLIST
        run: |
          cobj EMPWRITE.cbl EMPLIST.cbl
          java EMPWRITE
          java EMPLIST > EMPLIST.log
          cat EMPLIST.log

      - name: EMPLIST old and new comparison
        continue-on-error: true
        run: |
          diff EMPLIST.old EMPLIST.log
      
      - name: Run EMPSEARCH and EMPREAD
        run: |
          cobj EMPSEARCH.cbl EMPREAD.cbl
          echo 0011 | java EMPSEARCH

      - name: Run EmpSearchDemo
        run: |
          javac EmpSearchDemo.java
          java EmpSearchDemo

