name: Run cobol sample
on:
  workflow_dispatch:
  push:
    
jobs:
  run-sample-program:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential bison flex gettext texinfo automake autoconf
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install opensource COBOL 4J
        run: |
          mkdir opensourcecobol4j
          mkdir ~/.java_lib
          curl -L -o ~/.java_lib/sqlite.jar https://github.com/xerial/sqlite-jdbc/releases/download/3.36.0.3/sqlite-jdbc-3.36.0.3.jar
          export CLASSPATH=":$HOME/.java_lib/sqlite.jar"
          cd opensourcecobol4j
          ./configure --prefix=/usr/
          make
          sudo make install
          echo "CLASSPATH=:/usr/lib/opensourcecobol4j/libcobj.jar:$HOME/.java_lib/sqlite.jar" >> $GITHUB_ENV
      - name: Compile sample programs
        run: |
          export JAVA_INC=/usr/lib/jvm/temurin-17-jdk-amd64/include
          cobj EMPWRITE.cbl
          java EMPWRITE
          
          
