name: Run cobol sample
on:
  workflow_dispatch:
  push:
    
jobs:
  run-sample-program:
    runs-on: ubuntu-latest
    container:
      image: opensourcecobol/opensourcecobol4j
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Show cobj version
        run: |
          cobj -version

      - name: Run HELLO
        run: |
          cobj HELLO.cbl
          echo mytest | java HELLO

      - name: Run EMPWRITE and EMPLIST
        run: |
          cobj EMPWRITE.cbl EMPLIST.cbl
          java EMPWRITE
          java EMPLIST
      
      - name: Run EMPSEARCH and EMPREAD
        run: |
          cobj EMPSEARCH.cbl EMPREAD.cbl
          echo 0011 | java EMPSEARCH

      - name: Run EmpSearchDemo
        run: |
          javac EmpSearchDemo.java
          java EmpSearchDemo

